---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kube-stats.intodevops.com
  resources:
  - stats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-stats.intodevops.com
  resources:
  - stats/finalizers
  verbs:
  - update
- apiGroups:
  - kube-stats.intodevops.com
  resources:
  - stats/status
  verbs:
  - get
  - patch
  - update
